### PR TITLE
Update VikingMiniMap.lua

### PR DESCRIPTION
**Pull request by Zeirk**
White dot in addon list fix.

### CODE REVIEW

**Comment by mkaito** [comment]
Seems this brings up other issues:

```
...SOFT\WildStar\Addons\VikingMiniMap\VikingMiniMap.lua:1910: attempt to index global     'VikingMinimapInst' (a nil value)
stack trace:
...SOFT\WildStar\Addons\VikingMiniMap\VikingMiniMap.lua:1910: in main chunk
```

**Comment by Zeirk** [comment]
Woops, just swap the captial M for a lowercase in map, fixes it, I should have tested that on my minimap before hand, I tested it now and it indeed breaks it, just swapping that m fixes it though. I'm not sure why that wasn't included in your minimap, it's always been working fine for me.

**Comment by mkaito** [comment]
There was some caps swapping in degenerated's changes, I must have missed that. Could you commit the change to your branch so I can merge it cleanly? Just change it on your side and it'll show up here when you push.

**Comment by mkaito** [comment]
Actually, is there any difference between the MiniMap we got from degenerated and the default Carbine minimap?

**Comment by Zeirk** [comment]
It's square? I think that's it mainly, haven't looked too much into the minimap cause it's exactly what I wanted, though rectangle would be cool as well.

**Comment by mkaito** [comment]
It's... not square for me. Not in game, and not in Houston either.

A freely resizeable square, perhaps with simplified icons, is all we really need. The minimap doesn't _do_ much.

**Comment by Zeirk** [comment]
Ok, go into houston, open the XML, click MapContent and go to Mini Map tab, and just delete the mask, save and reloadui, bam square. There's some other stuff to delete in the sprites as well.

**Comment by mkaito** [comment]
Did that. Map is square now, but still has this round shadow with the N and S on it. Can't seem to figure out what that is linked to.

Messing around with item placement and making things fade in on mouse over.

**Comment by Zeirk** [comment]
Yea, I'm still trying to figure out how to get rid of it.

**Comment by mkaito** [comment]
I'll push this changeset and open an issue. Someone might know how to fix it.

**Pull request closed without merging**
